

#Constantes
TIPO_DATABASE = 'mysql'
USER_DATABASE = 'root'
SENHA_DATABASE = 'forensics'
PORTA = '3306'
NOME_DATABASE = 'pagarMe'
ECHO = True


DATABASE_CONFIG = TIPO_DATABASE+'://'+USER_DATABASE +':'+SENHA_DATABASE+'@localhost:'+PORTA+'/'+NOME_DATABASE